#!/usr/bin/env python3
"""Email session review via Claude API + Resend."""

import json
import os
import sqlite3
import sys
import time
from datetime import datetime
from pathlib import Path

from anthropic import Anthropic, RateLimitError
from dotenv import load_dotenv

DB_PATH = Path.home() / ".claude" / "prompt-history.db"
REPO_DIR = Path(__file__).resolve().parent
SONNET = "claude-sonnet-4-6"


def get_db():
    db = sqlite3.connect(DB_PATH)
    db.row_factory = sqlite3.Row
    return db


def query_sessions(db, days):
    return db.execute("""
        SELECT project, date(started_at) as date, summary, started_at
        FROM sessions
        WHERE summary IS NOT NULL
          AND started_at >= datetime('now', printf('-%d days', ?))
        ORDER BY started_at DESC
    """, (days,)).fetchall()


def query_daily_summaries(db, days):
    return db.execute("""
        SELECT date, project, summary
        FROM daily_summaries
        WHERE date >= date('now', printf('-%d days', ?))
        ORDER BY date DESC
    """, (days,)).fetchall()


def build_prompt(daily_sessions, daily_summaries_1d, weekly_sessions, weekly_summaries, is_weekly):
    def format_sessions(sessions):
        return chr(10).join(f"[{s['date']}] {s['project']}: {s['summary']}" for s in sessions) or "(none)"

    def format_summaries(summaries):
        return chr(10).join(f"[{ds['date']}] {ds['project']}: {ds['summary']}" for ds in summaries) or "(none)"

    user_msg = f"""Date: {datetime.now().strftime('%Y-%m-%d')}

== Last 24 hours ==

Session summaries ({len(daily_sessions)}):
{format_sessions(daily_sessions)}

Daily summaries ({len(daily_summaries_1d)}):
{format_summaries(daily_summaries_1d)}

== This week (7 days) ==

Session summaries ({len(weekly_sessions)}):
{format_sessions(weekly_sessions)}

Daily summaries ({len(weekly_summaries)}):
{format_summaries(weekly_summaries)}"""

    weekly_emphasis = """
- The weekly recap section should be the main focus — identify themes, trajectory, and what's coming next
- Give the weekly section more depth and analysis""" if is_weekly else ""

    system = f"""You write email reviews of a developer's recent work sessions.

Write a combined review with two sections:
1. **Today** — a concise summary of the last 24 hours
2. **This Week** — a recap of the full 7-day period, highlighting themes and progress

Format rules:
- Group by project within each section (bold project names)
- Explain technical concepts briefly — spell out acronyms (e.g. "CI" → "Continuous Integration, the automated testing system"), mention what tools do
- Assume the reader is smart but not an engineer
- Keep a warm, informative tone — this is for someone who wants to understand and appreciate the work
- If there's no data for the daily section, say so briefly and focus on the weekly recap{weekly_emphasis}

HTML style guidelines:
- Use inline CSS only
- Font: -apple-system, system-ui, sans-serif
- Max width: 600px, centered
- Section headings: 18px bold, project headings: 16px bold
- Body text: 14px, line-height 1.5
- Muted footer with date and "Generated by Ground Control"
"""

    return system, user_msg


REVIEW_TOOL = {
    "name": "generate_review",
    "description": "Generate the email review with subject, HTML body, and plain text body.",
    "input_schema": {
        "type": "object",
        "properties": {
            "subject": {"type": "string", "description": "One-line email subject"},
            "html": {"type": "string", "description": "Full HTML email body"},
            "text": {"type": "string", "description": "Plain text version of the email"},
        },
        "required": ["subject", "html", "text"],
    },
}


def call_claude(client, system, user_msg, max_retries=3):
    for attempt in range(max_retries):
        try:
            resp = client.messages.create(
                model=SONNET,
                max_tokens=16384,
                system=system,
                messages=[{"role": "user", "content": user_msg}],
                tools=[REVIEW_TOOL],
                tool_choice={"type": "tool", "name": "generate_review"},
            )
            return resp.content[0].input, resp.usage
        except RateLimitError:
            if attempt < max_retries - 1:
                wait = 2 ** (attempt + 1)
                print(f"Rate limited, waiting {wait}s...")
                time.sleep(wait)
            else:
                raise


def send_email(subject, html, text):
    import urllib.request

    api_key = os.environ.get("RESEND_API_KEY")
    if not api_key:
        print("Error: RESEND_API_KEY not set", file=sys.stderr)
        sys.exit(1)

    from_email = os.environ.get("REVIEW_FROM_EMAIL")
    to_email = os.environ.get("REVIEW_TO_EMAIL")
    if not from_email or not to_email:
        print("Error: REVIEW_FROM_EMAIL and REVIEW_TO_EMAIL must be set in .env", file=sys.stderr)
        sys.exit(1)

    payload = json.dumps({
        "from": from_email,
        "to": [to_email],
        "subject": subject,
        "html": html,
        "text": text,
    }).encode()

    req = urllib.request.Request(
        "https://api.resend.com/emails",
        data=payload,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "User-Agent": "prompt-lab/1.0",
        },
    )

    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"Resend API error {e.code}: {body}", file=sys.stderr)
        sys.exit(1)


def main():
    dry_run = "--dry-run" in sys.argv

    # Load environment
    env_path = REPO_DIR / ".env"
    synth_env = Path.home() / ".claude" / "synthesizer.env"
    if env_path.exists():
        load_dotenv(env_path)
    if synth_env.exists():
        load_dotenv(synth_env, override=False)

    if not os.environ.get("ANTHROPIC_API_KEY"):
        print("Error: ANTHROPIC_API_KEY not found in .env or ~/.claude/synthesizer.env", file=sys.stderr)
        sys.exit(1)

    # Saturday = more reflective weekly tone; always fetch both windows
    today = datetime.now()
    is_weekly = today.weekday() == 5

    db = get_db()
    daily_sessions = query_sessions(db, 1)
    daily_summaries_1d = query_daily_summaries(db, 1)
    weekly_sessions = query_sessions(db, 7)
    weekly_summaries = query_daily_summaries(db, 7)
    db.close()

    if not weekly_sessions and not weekly_summaries:
        print("No sessions or summaries found for the period.")
        return

    system, user_msg = build_prompt(daily_sessions, daily_summaries_1d, weekly_sessions, weekly_summaries, is_weekly)

    client = Anthropic()
    t0 = time.time()
    result, usage = call_claude(client, system, user_msg)
    elapsed = time.time() - t0

    subject = result.get("subject", "Session Review")
    html = result.get("html", "")
    text = result.get("text", "")

    print(f"Generated review in {elapsed:.1f}s ({usage.input_tokens}+{usage.output_tokens} tokens)")
    print(f"Subject: {subject}")
    print(f"Model: {SONNET}")
    print(f"Mode: {'weekly (Saturday)' if is_weekly else 'daily'} — both 1d + 7d windows")

    if dry_run:
        print(f"\n{'=' * 60}")
        print(text)
        print(f"{'=' * 60}")
        print("(dry run, not sent)")
        return

    result = send_email(subject, html, text)
    print(f"Sent (id: {result.get('id', '?')})")


if __name__ == "__main__":
    main()
