#!/usr/bin/env python3
"""Email session review via Claude API + Resend."""

import json
import os
import sys
from datetime import datetime

from anthropic import Anthropic

import heartbeat
from claude_api import SONNET, call_claude, load_env
from store import get_store

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "web"))
from day_helper import lab_days_ago  # noqa: E402


def review_windows():
    """The email's two windows, on the lab's clock.

    "Today" is *yesterday's completed lab-day*, never the run date: the job
    fires at 2:30am, when the run date structurally has no summaries yet —
    asking for "today" is how the email said "no new work" on days with 25
    prompts across 4 projects.
    """
    return {
        "review_day": lab_days_ago(1),
        "week_since": lab_days_ago(7),
    }


REVIEW_TOOL = {
    "name": "generate_review",
    "description": "Generate the email review with subject, HTML body, and plain text body.",
    "input_schema": {
        "type": "object",
        "properties": {
            "subject": {"type": "string", "description": "One-line email subject"},
            "html": {"type": "string", "description": "Full HTML email body"},
            "text": {"type": "string", "description": "Plain text version of the email"},
        },
        "required": ["subject", "html", "text"],
    },
}


def build_prompt(daily_summaries_1d, weekly_summaries, weekly_rollups, is_weekly):
    def format_summaries(summaries):
        lines = []
        for ds in summaries:
            counts = f" ({ds.get('prompt_count') or 0} prompts, {ds.get('session_count') or 0} sessions)"
            lines.append(f"[{ds['date']}] {ds['project']}{counts}: {ds['summary']}")
        return chr(10).join(lines) or "(none)"

    def format_rollups(rollups):
        if not rollups:
            return "(none)"
        lines = []
        for r in rollups:
            lines.append(f"[{r['project']} / week of {r['week_start']}] {r['narrative']}")
        return chr(10).join(lines)

    rollup_section = ""
    if weekly_rollups:
        rollup_section = f"""

== Weekly rollups (pre-synthesized) ==

{format_rollups(weekly_rollups)}
"""

    user_msg = f"""Date: {datetime.now().strftime('%Y-%m-%d')}

== Last 24 hours ==

Daily summaries ({len(daily_summaries_1d)}):
{format_summaries(daily_summaries_1d)}

== This week (7 days) ==

Daily summaries ({len(weekly_summaries)}):
{format_summaries(weekly_summaries)}{rollup_section}"""

    weekly_emphasis = """
- The weekly recap section should be the main focus — identify themes, trajectory, and what's coming next
- Give the weekly section more depth and analysis""" if is_weekly else ""

    system = f"""You write email reviews of a developer's recent work sessions.

Write a combined review with two sections:
1. **Today** — a concise summary of the last 24 hours
2. **This Week** — a recap of the full 7-day period, highlighting themes and progress

Format rules:
- Group by project within each section (bold project names)
- Explain technical concepts briefly — spell out acronyms (e.g. "CI" → "Continuous Integration, the automated testing system"), mention what tools do
- Assume the reader is smart but not an engineer
- Keep a warm, informative tone — this is for someone who wants to understand and appreciate the work
- If there's no data for the daily section, say so briefly and focus on the weekly recap{weekly_emphasis}

HTML style guidelines:
- Use inline CSS only
- Font: -apple-system, system-ui, sans-serif
- Max width: 600px, centered
- Section headings: 18px bold, project headings: 16px bold
- Body text: 14px, line-height 1.5
- Muted footer with date and "Generated by Ground Control"
"""

    return system, user_msg


def send_email(subject, html, text):
    import urllib.request

    api_key = os.environ.get("RESEND_API_KEY")
    if not api_key:
        print("Error: RESEND_API_KEY not set", file=sys.stderr)
        sys.exit(1)

    from_email = os.environ.get("REVIEW_FROM_EMAIL")
    to_email = os.environ.get("REVIEW_TO_EMAIL")
    if not from_email or not to_email:
        print("Error: REVIEW_FROM_EMAIL and REVIEW_TO_EMAIL must be set in .env", file=sys.stderr)
        sys.exit(1)

    payload = json.dumps({
        "from": from_email,
        "to": [to_email],
        "subject": subject,
        "html": html,
        "text": text,
    }).encode()

    req = urllib.request.Request(
        "https://api.resend.com/emails",
        data=payload,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "User-Agent": "prompt-lab/1.0",
        },
    )

    # Returns None on failure rather than exiting: the caller still has a
    # generated review worth persisting, and dying here is what hid a 403 for
    # 60 nights — the snapshot never landed, so the DB looked like the job had
    # stopped running instead of failing at the last step.
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"Resend API error {e.code}: {body}", file=sys.stderr)
        return None


def main():
    dry_run = "--dry-run" in sys.argv

    # Load environment
    load_env()

    # Exercises the Resend path only — no Claude call, so verifying a
    # from-address or API-key change is free and takes a second rather than
    # two minutes of generation.
    if "--test-send" in sys.argv:
        body = "Test send from send-review.py. If this arrived, Resend is configured correctly."
        if send_email("Prompt Lab — review email test send", f"<p>{body}</p>", body) is None:
            sys.exit(1)
        print("Test send OK.")
        return

    if not os.environ.get("ANTHROPIC_API_KEY"):
        print("Error: ANTHROPIC_API_KEY not found. Set it in .env.local", file=sys.stderr)
        sys.exit(1)

    # Saturday = more reflective weekly tone; always fetch both windows
    today = datetime.now()
    is_weekly = today.weekday() == 5
    today_str = today.strftime("%Y-%m-%d")
    w = review_windows()

    # Reads come from the merged store: processed tables in Turso carry every
    # machine's summaries, so the email covers all work no matter which
    # machine sends it. The raw tier is machine-local by invariant and must
    # never be read here — that's how the email said "no new work" on busy
    # days. Turso being unreachable raises and kills the run: no email, a
    # stale artifact, and the #45 heartbeat catches it — never a confidently
    # empty email.
    store = get_store("turso")
    daily_summaries_1d = store.get_daily_summaries(
        since=w["review_day"], until=w["review_day"])
    weekly_summaries = store.get_daily_summaries(since=w["week_since"])
    weekly_rollups = store.get_weekly_rollups(since=w["week_since"])
    store.close()

    if not weekly_summaries and not weekly_rollups:
        print("No summaries or rollups found for the period.")
        return

    system, user_msg = build_prompt(daily_summaries_1d, weekly_summaries,
                                     weekly_rollups, is_weekly)

    client = Anthropic()
    result = call_claude(client, model=SONNET, system=system, user_msg=user_msg,
                         tool=REVIEW_TOOL, max_tokens=16384)

    subject = result["parsed"].get("subject", "Session Review")
    html = result["parsed"].get("html", "")
    text = result["parsed"].get("text", "")

    print(f"Generated review in {result['duration_ms']/1000:.1f}s "
          f"({result['input_tokens']}+{result['output_tokens']} tokens)")
    print(f"Subject: {subject}")
    print(f"Model: {SONNET}")
    print(f"Mode: {'weekly (Saturday)' if is_weekly else 'daily'} — both 1d + 7d windows")

    if dry_run:
        print(f"\n{'=' * 60}")
        print(text)
        print(f"{'=' * 60}")
        print("(dry run, not sent)")
        return

    email_result = send_email(subject, html, text)
    if email_result is None:
        print("Send FAILED — persisting the review anyway.", file=sys.stderr)
    else:
        print(f"Sent (id: {email_result.get('id', '?')})")

    # Persist the review
    store = get_store()
    store.migrate()
    store.save_review_snapshot(
        review_type="weekly_email" if is_weekly else "daily_email",
        date=today_str, subject=subject,
        content_html=html, content_text=text,
        model=SONNET, input_tokens=result["input_tokens"],
        output_tokens=result["output_tokens"],
    )
    store.close()

    # Gated on the send, not on reaching this line. The 60-night outage looked
    # exactly like a healthy run right up to Resend's 403 — a heartbeat that
    # fired on "the process finished" would have reported fresh throughout.
    if email_result is not None:
        heartbeat.ping("review")

    # Non-zero last, after the snapshot is safe, so launchd records the failure.
    if email_result is None:
        sys.exit(1)


if __name__ == "__main__":
    main()
