"""Draft a reviewable public-refresh artifact for one project.

Step 1 of the draft-to-artifact publish flow that replaced the one-shot
`backfill_public_*.py` scripts as the way public data gets refreshed.

    draft  (this script)  -> drafts/public-<project>-<date>.md
    review (human)        -> read it, scrub the PUBLIC blocks, commit
    publish               -> scripts/publish_public_draft.py <file> --apply

Why a draft file and not a direct write: the public tables' safety property
is "reviewed, git-committed literal, published by a deliberate act" — not
"generated by a trustworthy process". `/handoff` used to write these tables
live; that was removed 2026-06-13 because it fired for every repo including
client work and auto-propagated to public Turso on the next sync. This flow
keeps the review gate while making a refresh cheap enough to actually happen.

This script only ever READS. It writes one markdown file and touches no table.

Usage:
    .venv/bin/python scripts/draft_public_refresh.py musicforge
    .venv/bin/python scripts/draft_public_refresh.py musicforge --all
    .venv/bin/python scripts/draft_public_refresh.py --list
"""

import argparse
import sys
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from store import get_store  # noqa: E402

DRAFTS_DIR = REPO / "drafts"

HEADER = """# Public refresh draft — {project}

<!-- generated: {today} -->
<!-- last published week_of: {last_published} -->
<!-- unpublished weeks found: {n} -->

Rewrite each **PUBLIC** block below into text safe for an unauthenticated,
permanently-public endpoint, then commit this file and run:

    .venv/bin/python scripts/publish_public_draft.py {relpath} --apply

The PRIVATE block under each week is unreviewed synthesizer output over raw
prompts. It is source material, not a starting draft — it routinely contains
client and collaborator names, absolute paths, unreleased plans, and vendor
detail. Do not lightly edit it; write the public version from scratch.

Leave a PUBLIC block as `TODO` to skip that week entirely. Skipped weeks stay
unpublished and will reappear in the next draft.

Aim for what a stranger reading a portfolio should see: what was built and why
it mattered. No issue numbers, no people, no infrastructure specifics.

---
"""

WEEK_BLOCK = """
## WEEK {week_start}

sessions: {session_count}
commits: {commit_count}

### PRIVATE — source material, do not publish

{private}

### PUBLIC

TODO
"""


def quote(text: str) -> str:
    """Blockquote every line so a stray '## ' in the prose can't fake a block."""
    text = (text or "").strip() or "(no narrative)"
    return "\n".join("> " + line for line in text.splitlines())


def gather(store, project: str) -> tuple[list[dict], str | None]:
    """Return (unpublished rollups oldest-first, last published week_of)."""
    names = store.expand_project(project)

    published = {
        r["week_of"]
        for r in store.get_public_weekly_rollups()
        if r["project"] in names
    }
    last_published = max(published) if published else None

    private = [
        r for r in store.get_weekly_rollups()
        if r["project"] in names
    ]
    unpublished = [r for r in private if r["week_start"] not in published]
    unpublished.sort(key=lambda r: r["week_start"])
    return unpublished, last_published


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("project", nargs="?", help="project / historyKey to draft")
    ap.add_argument("--all", action="store_true",
                    help="include every unpublished week (default: last 8)")
    ap.add_argument("--list", action="store_true",
                    help="show per-project unpublished counts and exit")
    args = ap.parse_args()

    store = get_store()
    store.migrate()

    if args.list:
        pubs = store.get_public_weekly_rollups()
        canon = sorted({store.expand_project(r["project"])[0] for r in pubs})
        print("Projects with public rows (the publishable set):\n")
        for p in canon:
            unpub, last = gather(store, p)
            print(f"  {p:22s} last published {last or '(never)':12s} "
                  f"{len(unpub):3d} unpublished week(s)")
        print("\nA project absent here has never been published. Publishing a new "
              "one is a manifest decision — add it to docs/public-allowlist.txt "
              "and the consumer's MDX manifest first.")
        store.close()
        return 0

    if not args.project:
        ap.error("project is required unless --list is given")

    project = args.project
    unpublished, last_published = gather(store, project)

    if not unpublished:
        print(f"{project}: nothing to draft — public rows are current "
              f"(last published week_of {last_published or '(never)'}).")
        store.close()
        return 0

    if not args.all and len(unpublished) > 8:
        print(f"note: {len(unpublished)} unpublished weeks; drafting the most "
              f"recent 8. Use --all for the full backlog.")
        unpublished = unpublished[-8:]

    today = date.today().isoformat()
    DRAFTS_DIR.mkdir(exist_ok=True)
    out = DRAFTS_DIR / f"public-{project}-{today}.md"
    relpath = out.relative_to(REPO)

    body = HEADER.format(
        project=project, today=today, relpath=relpath,
        last_published=last_published or "(never)", n=len(unpublished),
    )
    for r in unpublished:
        body += WEEK_BLOCK.format(
            week_start=r["week_start"],
            session_count=r.get("session_count") or 0,
            commit_count=r.get("commit_count") or 0,
            private=quote(r.get("narrative")),
        )

    out.write_text(body)
    store.close()

    print(f"Wrote {relpath} — {len(unpublished)} week(s) awaiting review.")
    print("\nNext: fill each PUBLIC block, commit the file, then run")
    print(f"  .venv/bin/python scripts/publish_public_draft.py {relpath} --apply")
    return 0


if __name__ == "__main__":
    sys.exit(main())
